### PR TITLE
completed tests for Product endpoints create, retrieve, and list

### PR DESCRIPTION
**Pull request by schatfield**
Wrote tests for Product endpoints. Please check that the post, get, and list tests run and pass.

Instructions for testing the tests:

git fetch --all
git checkout sc-secondBranch
run python manage.py in the terminal
confirm that the tests pass in terminal

### CODE REVIEW

**Comment by schatfield** [comment]
Hey guys, I fixed the error. Cab you take another look?

**Review by Belljeremiah — APPROVED** [review]
Works great after the update Tests are coming right along!

**Review by josephwalker504 — APPROVED** [review]
changes fix code test is working properly

**Review by MatthewScott32 — APPROVED** [review]
Looks good to me Shawna

**Pull request merged**
