### PR TITLE
Ep product types

### PR DESCRIPTION
**Pull request by erinepolley**
`git fetch --all`
`git checkout ep-product-types`
Please test all my methods in views/producttypes.py. They are list, retrieve, create, update, and destroy.
localhost:8000/producttypes
The only attribute on product type is name.

### CODE REVIEW

**Review by josephwalker504 — APPROVED** [review]
conducted POST, PUT,  GET AND DELETE all methods worked properly

**Review by MatthewScott32 — APPROVED** [review]
Full functionality worked for me with crud

**Review by schatfield — APPROVED** [review]
All methods are functional through postman. Good job!

**Review by Belljeremiah — APPROVED** [review]
Tested in postman and working great! Good Job Erin!

**Pull request merged**
