### PR TITLE
made models

### PR DESCRIPTION
**Pull request by MatthewScott32**
git fetch --all
git checkout mb-initialBranch
make sure all the models we made are there and the init is gouda

### CODE REVIEW

**Review by schatfield — APPROVED** [review]
very good job

**Comment by MatthewScott32** [comment]
> very good job

Thank you shawna

**Review by rhc822 — APPROVED** [review]
All good, thanks

**Comment by MatthewScott32** [comment]
> All good, thanks

No. Thank you

**Comment by rhc822** [comment]
> > All good, thanks
> 
> No. Thank you

Yes

**Pull request merged**
